---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyanlun.
--- DateTime: 2024/11/14 14:25
---
--- 参数列表：
--- 优惠券id
local voucherId = ARGV[1]
--- 用户id
local userId = ARGV[2]
---订单id
local orderId = ARGV[3]

---数据key：
---库存key
local stockKey = 'seckill:stock:' .. voucherId
---订单key
local orderKey = 'seckill:order:' .. voucherId

---判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    ---不足返回1
    return 1
end

---判断用户是否下单
if(redis.call('sismember',orderKey,userId) == 1) then
---存在，则重复下单返回2
    return 2
end

---扣库存
redis.call('incrby',stockKey,-1)
---下单保存用户
redis.call('sadd',orderKey,userId)
---发消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0